# largely copied from https://coderefinery.github.io/documentation/gh_workflow/
name: update-docs

on: [push, pull_request, workflow_dispatch]

permissions:
  id-token: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          sphinx-build . _build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _build/
      - uses: actions/deploy-pages@v4
